name: Detour
version: 1.4.2
description: Плагин для обхода игроков
author: AlphaCH1337
authors: [AlphaCH1337, OgyreZ_1]
main: ru.alphach1337.detour.Detour
database: true

commands:
  detour:
    description: Плагин для обхода игроков
    start:
      description: Начинает обход
      permission: detour.manage
      usage: /detour start
    stop:
      description: Заканчивает обход
      permission: detour.manage
      usage: /detour stop
    next:
      descrption: Следующий игрок
      permission: detour.manage
      usage: /detour next
    join:
      description: Присоединиться к обходу
      permission: detour.member
      usage: /detour join
    quit:
      description: Выйти из обхода
      permission: detour.member
      usage: /detour quit
    list:
      description: Посмотреть очередь обхода
      permission: detour.member
      usage: /detour list
    usage: /detour [start, stop, join, next, quit, list]
permissions:
  detour.*:
    description: Дает доступ ко всем командам обхода
    children:
      detour.manage: true
      detour.member: true
  detour.manage:
    description: Дает доступ к командам start, stop
    default: false
  detour.member:
    description: Дает доступ к командам join, quit, list
    default: true
